# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'https-lenpaul-github-io-lagrange'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'victoryang1653'

menu:
- {name: 'About',   url: 'about.html'}
- {name: 'People', url: 'people.html'}
- {name: 'Publications', url: 'publications.html'}
- {name: 'Projects', url: 'projects.html'}
- {name: 'Teaching', url: 'teaching.html'}
- {name: 'News', url: 'news.html'}


# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'linkedin',   link: 'https://www.linkedin.com/in/wookjae-yang-97292a174/'}
- {icon: 'google', link: 'https://scholar.google.com/citations?user=Sj8naFQAAAAJ&hl=en'}
- {icon: 'github',     link: 'https://github.com/wookjaeyang-inu'}
- {icon: 'envelope',   link: 'mailto:wookjae.yang@inu.ac.kr'}




# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy:'

post_date_prefix: 'Written on'
